DROP TABLE IF EXISTS INE_MUNICIPIO;
DROP TABLE IF EXISTS INE_PROVINCIA;

CREATE TABLE INE_PROVINCIA (
    CPRO INT PRIMARY KEY, -- CÓDIGO DE PROVINCIA
    NOMBRE VARCHAR(255),  -- NOMBRE DE PROVINCIA
    CODAUTO INT,          -- CÓDIGO DE CCAA
    CCAA VARCHAR(255)     -- NOMBRE COMUNIDAD AUTÓNOMA
);

CREATE TABLE INE_MUNICIPIO (
    CMUN INT, -- CÓDIGO DE MUNICIPIO
    CPRO INT, -- CÓDIGO DE PROVINCIA
    DC INT,   -- DÍGITO DE CONTROL
    NOMBRE VARCHAR(255),
    PRIMARY KEY (CPRO, CMUN),
    FOREIGN KEY (CPRO) REFERENCES INE_PROVINCIA(CPRO)
);

INSERT INTO INE_PROVINCIA (CPRO, NOMBRE, CODAUTO, CCAA) VALUES 
(28, 'Madrid', 13, 'Comunidad de Madrid'),
(47, 'Valladolid', 07, 'Castilla y León'),
(39, 'Cantabria', 06, 'Cantabria'),
(41, 'Sevilla', 01, 'Andalucía');

INSERT INTO INE_MUNICIPIO (CMUN, CPRO, DC, NOMBRE) VALUES 
(079, 28, 6, 'Madrid'),
(186, 47, 4, 'Valladolid'),
(075, 39, 9, 'Santander'),
(091, 41, 2, 'Sevilla');